required = [
  "github.com/pebbe/zmq4"
]

[[constraint]]
  name = "gopkg.in/inf.v0"
  version = "0.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/jancajthaml-openbank/actor-system"
