version: 1

update_configs:
  - package_manager: "go:modules"
    directory: "/services/vault-rest"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/services/vault-unit"
    update_schedule: "daily"
